name: Dependency Review

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write # for submitting dependency graph
  pull-requests: write # for comment-summary-in-pr

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: johnpangalos/sbt-dependency-submission@133e9712e4d90d8e48a5902a0ee2264e24d264d3
      - uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request'
        with:
          comment-summary-in-pr: always
