name: Dependency Review

on:
  pull_request:

permissions:
  contents: write # for submitting dependency graph
  pull-requests: write # for comment-summary-in-pr

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v2
      - uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: always
