name: Dependency Graph

on:
  push:
    branches:
      - master

permissions:
  contents: write # this permission is needed to submit the dependency graph

jobs:
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: scalacenter/sbt-dependency-submission@v2

