name: Dependency Review

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write # for submitting dependency graph
  pull-requests: write # for comment-summary-in-pr

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: scalacenter/sbt-dependency-submission@ddf704f013d7d84f1c01a93411054cecd92224b7 # v2
      - uses: actions/dependency-review-action@cc4f6536e38d1126c5e3b0683d469a14f23bfea4 # v3
        if: github.event_name == 'pull_request'
        with:
          comment-summary-in-pr: always
