name: Dependency Review

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write # for submitting dependency graph
  pull-requests: write # for comment-summary-in-pr

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: olafurpg/setup-scala@v11
      - uses: scalacenter/sbt-dependency-submission@ddf704f013d7d84f1c01a93411054cecd92224b7 # v2
      - uses: actions/dependency-review-action@v3
        if: github.event_name == 'pull_request'
        with:
          comment-summary-in-pr: always
